insert into authors (id, last_name, first_name, description, photo_id) values (1, 'Peplaw', 'Freddy', 'Bonne Bell LLC', 8);
insert into authors (id, last_name, first_name, description, photo_id) values (2, 'Bulteel', 'Dorothy', 'KAISER FOUNDATION HOSPITALS', 8);
insert into authors (id, last_name, first_name, description, photo_id) values (3, 'Mirralls', 'Nil', 'Actavis Elizabeth LLC', 2);
insert into authors (id, last_name, first_name, description, photo_id) values (4, 'Shee', 'Filmer', 'PRESCRIPTIVES INC', 1);
insert into authors (id, last_name, first_name, description, photo_id) values (5, 'Debell', 'Marc', 'West-ward Pharmaceutical Corp', 4);
insert into authors (id, last_name, first_name, description, photo_id) values (6, 'Lampert', 'Maison', 'Nelco Laboratories, Inc.', 4);
insert into authors (id, last_name, first_name, description, photo_id) values (7, 'Grumell', 'Devina', 'A&Z Pharmaceutical, Inc.', 7);
insert into authors (id, last_name, first_name, description, photo_id) values (8, 'Etches', 'Sergeant', 'Dynarex Corporation', 10);
insert into authors (id, last_name, first_name, description, photo_id) values (9, 'Feild', 'Marice', 'Unit Dose Services', 6);
insert into authors (id, last_name, first_name, description, photo_id) values (10, 'Yearne', 'Emory', 'Laboratoire Dr. Renaud', 7);
insert into authors (id, last_name, first_name, description, photo_id) values (11, 'Ollcott', 'Emelen', 'Nelco Laboratories, Inc.', 2);
insert into authors (id, last_name, first_name, description, photo_id) values (12, 'Briers', 'Kelsey', 'Amneal Pharmaceuticals', 9);
insert into authors (id, last_name, first_name, description, photo_id) values (13, 'Fiddyment', 'Dorotea', 'A&Z Pharmaceutical, Inc.', 9);
insert into authors (id, last_name, first_name, description, photo_id) values (14, 'Mattack', 'Josefina', 'Teva Pharmaceuticals USA Inc', 6);
insert into authors (id, last_name, first_name, description, photo_id) values (15, 'Sennett', 'Sallyanne', 'SHISEIDO AMERICAS CORPORATION', 10);
insert into authors (id, last_name, first_name, description, photo_id) values (16, 'Whittington', 'Eleanora', 'REMEDYREPACK INC.', 6);
insert into authors (id, last_name, first_name, description, photo_id) values (17, 'Yurikov', 'Adi', 'Publix Super Markets Inc', 4);
insert into authors (id, last_name, first_name, description, photo_id) values (18, 'Stockau', 'Arne', 'Apotheca Company', 8);
insert into authors (id, last_name, first_name, description, photo_id) values (19, 'Morilla', 'Ely', 'Rebel Distributors Corp', 5);
insert into authors (id, last_name, first_name, description, photo_id) values (20, 'Mohun', 'Ethe', 'Concept Laboratories, Inc.', 9);
